services:
  api:
    build: .
    container_name: rf-cascade-tool-api
    restart: always
    volumes:
      - .:/workspace
    environment:
      - POSTGRES_HOST=rf-cascade-tool-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=rfcascade
      - CLEAR_DB=True
    ports:
      - 5000:5000
    command: sleep infinity

  db:
    image: postgres:13.13
    container_name: rf-cascade-tool-db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=rfcascade
    volumes:
      - data:/var/lib/postgresql/data
  
  adminer:
    image: adminer:latest
    container_name: rf-cascade-adminer
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - 7777:8080
    environment:
      - ADMINER_DEFAULT_DRIVER=pgsql
      - ADMINER_DEFAULT_SERVER=rf-cascade-tool-db

volumes:
  data: